spring.application.name=searchnsnip

# Supabase Postgres Database Configuration
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?user=postgres.wbqvhrdcrplkbpfbofiu&password=EB1umJCBRFfWjrBo&sslmode=require
spring.datasource.username=postgres.wbqvhrdcrplkbpfbofiu
spring.datasource.password=EB1umJCBRFfWjrBo
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
